imports:
    - { resource: tables.yml }

services:
    
    furexp.postcomment.core:
        class: furexp\postcomment\core\postcomment
        arguments:
            - '@furexp.postcomment.data'
            - '@furexp.postcomment.settings'
            - '@auth'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
    
    furexp.postcomment.data:
        class: furexp\postcomment\core\data
        arguments:
            - '@furexp.postcomment.settings'
            - '@dbal.conn'
            - '@user'

    furexp.postcomment.settings:
        class: furexp\postcomment\core\settings
        arguments:
            - '@user'
            - '@config'
            - '@auth'
            - '%furexp.postcomment.table.postcomment%'
            - '%furexp.postcomment.table.like%'
            - '%core.root_path%'
            - '%core.php_ext%'

    furexp.postcomment.controller.main:
        class: furexp\postcomment\controller\main_controller
        arguments:
            - '@furexp.postcomment.core'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@language'
            - '@auth'
            - '@request'
            - '@dispatcher'

    furexp.postcomment.event.main:
        class: furexp\postcomment\event\main_listener
        arguments:
            - '@furexp.postcomment.core'
            - '@config'
            - '@controller.helper'
            - '@user'
            - '@language'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }

    furexp.postcomment.event.acp:
        class: furexp\postcomment\event\acp_listener
        arguments:
            - '@furexp.postcomment.core'
            - '@controller.helper'
            - '@user'
            - '@language'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
